// Generated by CoffeeScript 1.7.1
(function($) {
  $(function() {
    $('#addTr').on('click', function(e) {
      var fila, template;
      e.preventDefault();
      template = $.templates("#trRoom");
      fila = $(template.render());
      $('a.deleteTrRoom', fila).on('click', function(e) {
        e.preventDefault();
        console.log(this);
        $(this).parent().parent().remove();
      });
      $('#tablaTarifas tbody').append(fila);
    });
    $('a.deleteTrRoom').on('click', function(e) {
      e.preventDefault();
      console.log(this);
      $(this).parent().parent().remove();
    });
  });
})(jQuery);
