-- MySQL Script generated by MySQL Workbench
-- Fri Aug 29 14:28:31 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema c1booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c1booking` DEFAULT CHARACTER SET latin1 ;
USE `c1booking` ;

-- -----------------------------------------------------
-- Table `c1booking`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c1booking`.`hotels` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `location` VARCHAR(150) NULL DEFAULT NULL,
  `stars` INT(11) NULL DEFAULT '1',
  `slug` VARCHAR(250) NULL DEFAULT NULL,
  `image` VARCHAR(250) NULL DEFAULT NULL,
  `room_count` INT(11) NULL DEFAULT '0',
  `active` INT(11) NULL DEFAULT '1',
  `description` TEXT NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `deleted` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c1booking`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c1booking`.`rooms` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `hotel_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `capacity` INT(11) NULL DEFAULT '2',
  `price` DOUBLE NULL DEFAULT NULL,
  `num_available` INT(11) NULL DEFAULT '1',
  `active` INT(11) NULL DEFAULT '1',
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hotel_id` (`hotel_id` ASC),
  CONSTRAINT `fk_rooms_hotels1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `c1booking`.`hotels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c1booking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c1booking`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `username` VARCHAR(50) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `rol` VARCHAR(50) NOT NULL DEFAULT 'usuario',
  `active` TINYINT(1) NULL DEFAULT '1',
  `created` DATETIME NULL DEFAULT NULL,
  `modified` INT(11) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `surname` VARCHAR(150) NULL DEFAULT NULL,
  `passwordreset` VARCHAR(150) NULL DEFAULT NULL,
  `newsletter` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC),
  INDEX `active` (`active` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `c1booking`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c1booking`.`bookings` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` INT(11) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `from` DATE NULL DEFAULT NULL,
  `to` DATE NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `active` INT(11) NULL DEFAULT '1',
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `paid` INT(11) NULL DEFAULT '0',
  `payment_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_users1_idx` (`user_id` ASC),
  INDEX `fk_bookings_rooms1_idx` (`room_id` ASC),
  CONSTRAINT `fk_bookings_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `c1booking`.`rooms` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `c1booking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `c1booking`.`rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c1booking`.`rates` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` INT(11) NULL DEFAULT NULL,
  `from` DATE NULL DEFAULT NULL,
  `to` DATE NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rates_rooms_idx` (`room_id` ASC),
  CONSTRAINT `fk_rates_rooms`
    FOREIGN KEY (`room_id`)
    REFERENCES `c1booking`.`rooms` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
